# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
import exiv2.metadatum
import exiv2.types
import exiv2.value

# Pull in all the attributes from the low-level C/C++ module
if __package__ or "." in __name__:
    from ._tags import *
else:
    from _tags import *


import enum
IfdId = enum.IntEnum('IfdId', _enum_list_IfdId())
IfdId.__doc__ = "Type to specify the IFD to which a metadata belongs.\n"
"\nMaker note IFDs have been omitted from this enum."


import enum
SectionId = enum.IntEnum('SectionId', _enum_list_SectionId())
SectionId.__doc__ = "Section identifiers to logically group tags.\n"
"\nA section consists of nothing more than a name, based on the"
"\nExif standard."


