# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Pull in all the attributes from the low-level C/C++ module
if __package__ or "." in __name__:
    from ._types import *
else:
    from _types import *


import os
_dir = os.path.join(os.path.dirname(__file__), 'locale')
if os.path.isdir(_dir):
    _set_locale_dir(_dir)


