name: Build MacOS wheels exiv2 0.28
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch Exiv2 source
        run: >
          wget -nv
          https://github.com/Exiv2/exiv2/archive/refs/tags/v0.28.4.tar.gz
          -O exiv2.tar.gz

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar -xzf exiv2.tar.gz
          mv exiv2-0.28.4 libexiv2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: x86_64
          CIBW_ENVIRONMENT: >
            EXIV2_ROOT=libexiv2/build-base_mac/install
            MACOSX_DEPLOYMENT_TARGET="13.0"
            SYSTEM_VERSION_COMPAT=0
          CIBW_SKIP: pp3*
          CIBW_TEST_COMMAND: >
            python -m exiv2 -v &&
            python -m unittest discover {project}/tests -v
          CIBW_BEFORE_ALL: >
            brew install ninja inih &&
            cd libexiv2 &&
            cmake --preset base_mac
            -D EXIV2_BUILD_SAMPLES=OFF
            -D EXIV2_BUILD_UNIT_TESTS=OFF
            -D EXIV2_ENABLE_NLS=ON
            -D EXIV2_ENABLE_FILESYSTEM_ACCESS=ON
            -D EXIV2_BUILD_EXIV2_COMMAND=OFF
            -D EXIV2_TEAM_WARNINGS_AS_ERRORS=OFF &&
            cmake --build build-base_mac --config Release &&
            cmake --install build-base_mac --config Release

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: macos-28-wheels
          path: wheelhouse/*.whl
