name: Build MacOS wheels exiv2 0.27
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch Exiv2 source
        run: >
          wget -nv
          https://github.com/Exiv2/exiv2/releases/download/v0.27.7/exiv2-0.27.7-Source.tar.gz
          -O exiv2.tar.gz

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar -xzf exiv2.tar.gz
          mv exiv2-0.27.7-Source libexiv2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS: x86_64
          CIBW_ENVIRONMENT: EXIV2_ROOT=libexiv2/build-macos/install
          CIBW_SKIP: pp3*
          CIBW_BEFORE_ALL: >
            brew install ninja gettext &&
            cd libexiv2 &&
            cmake . -B build-macos -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX=build-macos/install
            -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations"
            -DEXIV2_BUILD_SAMPLES=OFF
            -DEXIV2_BUILD_EXIV2_COMMAND=OFF
            -DEXIV2_ENABLE_BMFF=ON
            -DEXIV2_ENABLE_NLS=ON
            -DEXIV2_ENABLE_VIDEO=ON
            -DEXIV2_ENABLE_WEBREADY=ON
            -DEXIV2_ENABLE_CURL=ON
            -DEXIV2_ENABLE_SSH=ON
            -DCMAKE_CXX_STANDARD=98
            -G Ninja &&
            cmake --build build-macos &&
            cmake --install build-macos

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheel
          path: wheelhouse/*.whl

  test:
    needs: build
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v3
        with:
          name: macos-wheel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: pip3 install --disable-pip-version-check --no-index --find-links=. exiv2

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get package details
        run: python3 -m exiv2 -v

      - name: Run unit tests
        run: python3 -m unittest discover tests -v
