name: Build MacOS wheels exiv2 0.28
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch Exiv2 source
        run: >
          wget -nv
          https://github.com/Exiv2/exiv2/archive/refs/tags/v0.28.1.tar.gz
          -O exiv2.tar.gz

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar -xzf exiv2.tar.gz
          mv exiv2-0.28.1 libexiv2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS: x86_64
          CIBW_ENVIRONMENT: >
            EXIV2_ROOT=libexiv2/build-base_mac/install
            MACOSX_DEPLOYMENT_TARGET="11.0"
          CIBW_SKIP: pp3*
          CIBW_BEFORE_ALL: >
            brew install ninja inih &&
            cd libexiv2 &&
            cmake --preset base_mac
            -DEXIV2_BUILD_SAMPLES=OFF
            -DEXIV2_BUILD_UNIT_TESTS=OFF
            -DEXIV2_ENABLE_NLS=ON
            -DEXIV2_BUILD_EXIV2_COMMAND=OFF
            -DEXIV2_TEAM_WARNINGS_AS_ERRORS=OFF &&
            cmake --build build-base_mac &&
            cmake --install build-base_mac

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheel
          path: wheelhouse/*.whl

  test:
    needs: build
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v3
        with:
          name: macos-wheel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: >
          pip3 install --disable-pip-version-check --no-index
          --find-links=. exiv2

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get package details
        run: python3 -m exiv2 -v

      - name: Run unit tests
        run: python3 -m unittest discover tests -v
