name: Build Linux "manylinux" wheels
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.4
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
          system-packages: 'python3 python3-devel exiv2-devel swig pkgconfig'
          pre-build-command: 'python3 utils/build_swig.py system'
      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: manylinux-wheel
          path: dist/*.whl
