name: Build Windows wheels exiv2 0.28
on: workflow_dispatch

jobs:
  compile:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch Exiv2 source
        run: >
          c:\msys64\usr\bin\wget.exe -nv
          https://github.com/Exiv2/exiv2/archive/refs/tags/v0.28.1.tar.gz
          -O exiv2.tar.gz

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar -xzf exiv2.tar.gz
          mv exiv2-0.28.1 libexiv2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS: auto64
          CIBW_SKIP: pp3*
          CIBW_ENVIRONMENT: EXIV2_ROOT=libexiv2/build-msvc/install
          CIBW_TEST_COMMAND: >
            python -m exiv2 -v &&
            python -m unittest discover {project}/tests -v
          CIBW_BEFORE_ALL: >
            pip install conan==1.59.0 &&
            cd libexiv2 &&
            cmake --preset msvc
            -D CMAKE_BUILD_TYPE=Release
            -D EXIV2_BUILD_SAMPLES=OFF
            -D EXIV2_BUILD_EXIV2_COMMAND=OFF
            -D EXIV2_BUILD_UNIT_TESTS=OFF
            -G "Visual Studio 16 2019" &&
            cmake --build build-msvc --config Release &&
            cmake --install build-msvc --config Release &&
            copy build-msvc\bin\libcurl.dll build-msvc\install\bin

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheel
          path: wheelhouse/*.whl
