name: Build manylinux wheels
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: yum install exiv2-devel
          CIBW_ARCHS: auto64
          CIBW_SKIP: pp37-macosx_x86_64

      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: manylinux-wheel
          path: dist/*.whl
