name: Build manylinux wheels
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXIV2_ROOT: /project/exiv2-install
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download libexiv2
        run: |
          wget -nv https://github.com/Exiv2/exiv2/releases/download/v0.27.7/exiv2-0.27.7-Source.tar.gz
          tar xf exiv2-0.27.7-Source.tar.gz

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_ARCHS: auto64
          CIBW_ENVIRONMENT_PASS_LINUX: EXIV2_ROOT
          CIBW_BUILD: cp*-manylinux_x86_64
          CIBW_BEFORE_ALL: >
            yum install -y zlib-devel expat-devel gettext-devel &&
            cd exiv2-0.27.7-Source &&
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ env.EXIV2_ROOT }} \
              -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
              -DEXIV2_BUILD_SAMPLES=OFF \
              -DEXIV2_BUILD_EXIV2_COMMAND=OFF \
              -DEXIV2_ENABLE_BMFF=ON \
              -DEXIV2_ENABLE_NLS=ON \
              -DEXIV2_ENABLE_VIDEO=ON \
              -DCMAKE_CXX_STANDARD=98 &&
            cmake --build . &&
            cmake --install . &&
            cd ../.. &&
            python utils/build_swig.py ${{ env.EXIV2_ROOT }}/include

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: manylinux-wheel
          path: wheelhouse/*.whl

  test:
    needs: build
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest]
        include:
          - python-version: '3.6'
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v3
        with:
          name: manylinux-wheel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: pip3 install --disable-pip-version-check --no-index --find-links=. exiv2

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get package details
        run: python3 -m exiv2

      - name: Run unit tests
        run: python3 -m unittest discover tests
