name: Build manylinux wheels
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download libexiv2
        run: |
          wget -nv https://www.exiv2.org/builds/exiv2-0.27.4-Source.tar.gz
          tar xf exiv2-0.27.4-Source.tar.gz

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_ARCHS: auto64
          CIBW_SKIP: pp37-manylinux_x86_64
          CIBW_BEFORE_ALL: >
            yum install -y zlib-devel expat-devel &&
            cd exiv2-0.27.4-Source &&
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/usr \
              -DEXIV2_BUILD_SAMPLES=OFF \
              -DEXIV2_BUILD_EXIV2_COMMAND=OFF \
              -DEXIV2_ENABLE_BMFF=OFF &&
            cmake --build . &&
            make install &&
            cd ../.. &&
            python utils/build_swig.py system

      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: manylinux-wheel
          path: wheelhouse/*.whl

  test:
    needs: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v2
        with:
          name: manylinux-wheel

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: pip3 install --no-index --find-links=. python-exiv2

      - name: Test installation
        run: python3 -c "import exiv2; print(exiv2.__version__, exiv2.versionString())"
