name: Build Linux wheels exiv2 0.27
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch Exiv2 source
        run: >
          wget -nv
          https://github.com/Exiv2/exiv2/releases/download/v0.27.7/exiv2-0.27.7-Source.tar.gz
          -O exiv2.tar.gz

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar -xzf exiv2.tar.gz
          mv exiv2-0.27.7-Source libexiv2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS: auto64
          CIBW_ENVIRONMENT: EXIV2_ROOT=libexiv2/build-linux/install
          CIBW_BUILD: cp*-manylinux_x86_64
          CIBW_TEST_COMMAND: >
            python3 -m exiv2 -v &&
            python3 -m unittest discover {project}/tests -v
          CIBW_BEFORE_ALL: >
            yum install -y zlib-devel expat-devel gettext-devel
            libcurl-devel libssh-devel &&
            cd libexiv2 &&
            cmake -B build-linux -D CMAKE_BUILD_TYPE=Release
            -D CMAKE_INSTALL_PREFIX=build-linux/install
            -D CMAKE_CXX_FLAGS="-Wno-deprecated-declarations"
            -D EXIV2_BUILD_SAMPLES=OFF
            -D EXIV2_BUILD_EXIV2_COMMAND=OFF
            -D EXIV2_ENABLE_BMFF=ON
            -D EXIV2_ENABLE_NLS=ON
            -D EXIV2_ENABLE_VIDEO=ON
            -D EXIV2_ENABLE_WEBREADY=ON
            -D EXIV2_ENABLE_CURL=ON
            -D EXIV2_ENABLE_SSH=ON
            -D CMAKE_CXX_STANDARD=98 &&
            cmake --build build-linux &&
            cmake --install build-linux

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: manylinux-wheel
          path: wheelhouse/*.whl
