name: Build manylinux wheels
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_ALL: yum -y install exiv2-devel
          CIBW_ARCHS: auto64
          CIBW_SKIP: pp37-macosx_x86_64

      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: manylinux-wheel
          path: dist/*.whl
